apiVersion: v1
kind: Service
metadata:
  name: shape-color-app
  labels:
    app: shape-color-app
spec:
  selector:
    app: shape-color-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
